### ISSUE TITLE
Plugin installed but checklist not showing up in tickets

### ISSUE THREAD

**Issue by wwwindisch** [Undev/redmine_issue_checklist#41]
After updating a couple of redmine plugins, the checklist is not showing up in tickets anymore. It listed properly on the "Plugins" page in the admin account:

![image](https://user-images.githubusercontent.com/28566230/208418948-f3df17fd-286a-4663-8b71-afed5a2a1eea.png)

System Information:
```
Environment:
  Redmine version                4.1.3.stable
  Ruby version                   2.6.7-p197 (2021-04-05) [x86_64-linux]
  Rails version                  5.2.5
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Mercurial                      4.8.2
  Bazaar                         2.8.0
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  _query                         0.0.5
  a_common_libs                  2.5.7
  easy_mindmup                   1.0
  easy_wbs                       1.5
  external_links_in_new_window   0.9
  redmine_auto_resubmission      1.0.7
  redmine_checklists             3.1.21
  redmine_contacts               4.3.6
  redmine_issue_templates        1.1.0
  redmine_my_page_paginations    1.0.3
  sidebar_hide                   0.0.8
  unread_issues                  2.2.4
```

This is the output of `rake redmine:plugins:test NAME=redmine_issue_checklist RAILS_ENV=test_sqlite3` :
```
rake aborted!
ActiveRecord::AdapterNotSpecified: 'test_sqlite3' database is not configured. Available: ["production"]
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/connection_adapters/connection_specification.rb:260:in `resolve_symbol_connection'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/connection_adapters/connection_specification.rb:241:in `resolve_connection'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/connection_adapters/connection_specification.rb:143:in `resolve'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/connection_handling.rb:57:in `establish_connection'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/railtie.rb:136:in `block (2 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/lazy_load_hooks.rb:42:in `each'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/railtie.rb:132:in `block in <class:Railtie>'
/usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.5/lib/rails/application.rb:361:in `initialize!'
/usr/src/redmine/config/environment.rb:16:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/railties-5.2.5/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.5/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/src/redmine/lib/tasks/redmine.rake:161:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:test:units => db:test:prepare => db:load_config => environment
(See full trace by running task with --trace)
```

I've executed the install-commands (`bundle install` etc.) and restarted redmine after the plugin update.

EDIT: I also tried a complete reinstall using `bundle exec rake redmine:plugins:migrate NAME=redmine_checklists VERSION=0 RAILS_ENV=production`

Do you have suggestions on how to find the reason for this problem and fix it? Thanks a lot in advance.

**Comment by wwwindisch** [comment]
Problem solved: For some (unknown) reason the group permissions fror the plugin had been reset to default (none selected) by the update. Setting the right group permissions again has solved the problem.
