### ISSUE TITLE
Cannot close issue

### ISSUE THREAD

**Issue by casterx** [Undev/redmine_issue_checklist#5]
Hi, I've got this error while closing an issue that has checklist. Please help to fix it

```
Started PATCH "/issues/214/edit.js" for IP.X.Y.Z at 2015-05-01 11:38:33 +0700
Processing by IssuesController#edit as JS
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"_TOKEN_", "issue"=>{"is_private"=>"0", "project_id"=>"20", "tracker_id"=>"4", "subject"=>"Prepare development environment", "description"=>"Prepare development environment to upgrade to v2.0", "status_id"=>"5", "priority_id"=>"4", "assigned_to_id"=>"3", "category_id"=>"32", "fixed_version_id"=>"11", "parent_issue_id"=>"", "start_date"=>"2014-09-24", "due_date"=>"", "estimated_hours"=>"", "done_ratio"=>"100", "custom_field_values"=>{"11"=>"", "12"=>""}, "notes"=>"", "private_notes"=>"0", "lock_version"=>"1"}, "was_default_status"=>"1", "check_list_items"=>[{"subject"=>"Get source code from live server", "is_done"=>"1"}, {"subject"=>"Get database from live server", "is_done"=>"1"}, {"subject"=>"Create git repository", "is_done"=>"1"}, {"subject"=>"Upgrade Drupal core", "is_done"=>"1"}, {"subject"=>"Re-structure project", "is_done"=>"1"}, {"subject"=>"Upgrade contrib modules and themes", "is_done"=>"1"}, {"subject"=>"Upgrade database", "is_done"=>"1"}, {"subject"=>"Migrate data", "is_done"=>"1"}], "new_checklist"=>"", "time_entry"=>{"hours"=>"", "activity_id"=>"9", "comments"=>"", "custom_field_values"=>{"3"=>"Local"}}, "last_journal_id"=>"727", "id"=>"214"}
  Current user: root (id=1)
  Rendered issues/_form_custom_fields.html.erb (0.5ms)
  Rendered issues/_attributes.html.erb (113.5ms)
  Rendered plugins/redmine_issue_checklist/app/views/issues/_checklist_form.html.erb (2.0ms)
  Rendered issues/_form.html.erb (128.1ms)
  Rendered issues/edit.js.erb (129.1ms)
Completed 200 OK in 181ms (Views: 123.8ms | ActiveRecord: 14.9ms)
Started PATCH "/issues/214" for 116.100.132.149 at 2015-05-01 11:38:35 +0700
Processing by IssuesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"_TOKEN_", "issue"=>{"is_private"=>"0", "project_id"=>"20", "tracker_id"=>"4", "subject"=>"Prepare development environment", "description"=>"Prepare development environment to upgrade to v2.0", "status_id"=>"5", "priority_id"=>"4", "assigned_to_id"=>"3", "category_id"=>"32", "fixed_version_id"=>"11", "parent_issue_id"=>"", "start_date"=>"2014-09-24", "due_date"=>"", "estimated_hours"=>"", "done_ratio"=>"100", "custom_field_values"=>{"11"=>"", "12"=>""}, "notes"=>"", "private_notes"=>"0", "lock_version"=>"1"}, "check_list_items"=>[{"subject"=>"Get source code from live server", "is_done"=>"1"}, {"subject"=>"Get database from live server", "is_done"=>"1"}, {"subject"=>"Create git repository", "is_done"=>"1"}, {"subject"=>"Upgrade Drupal core", "is_done"=>"1"}, {"subject"=>"Re-structure project", "is_done"=>"1"}, {"subject"=>"Upgrade contrib modules and themes", "is_done"=>"1"}, {"subject"=>"Upgrade database", "is_done"=>"1"}, {"subject"=>"Migrate data", "is_done"=>"1"}], "new_checklist"=>"", "time_entry"=>{"hours"=>"", "activity_id"=>"9", "comments"=>"", "custom_field_values"=>{"3"=>"Local"}}, "last_journal_id"=>"727", "commit"=>"Submit", "id"=>"214"}
  Current user: root (id=1)
WARNING: Can't mass-assign protected attributes for IssueChecklist: is_done, subject
    lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
    lib/redmine/hook.rb:61:in `each'
    lib/redmine/hook.rb:61:in `block in call_hook'
    lib/redmine/hook.rb:58:in `tap'
    lib/redmine/hook.rb:58:in `call_hook'
    lib/redmine/hook.rb:162:in `call_hook'
    app/controllers/issues_controller.rb:478:in `block in save_issue_with_child_records'
    app/controllers/issues_controller.rb:467:in `save_issue_with_child_records'
    app/controllers/issues_controller.rb:180:in `update'
WARNING: Can't mass-assign protected attributes for IssueChecklist: is_done, subject
    lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
    lib/redmine/hook.rb:61:in `each'
    lib/redmine/hook.rb:61:in `block in call_hook'
    lib/redmine/hook.rb:58:in `tap'
    lib/redmine/hook.rb:58:in `call_hook'
    lib/redmine/hook.rb:162:in `call_hook'
    app/controllers/issues_controller.rb:478:in `block in save_issue_with_child_records'
    app/controllers/issues_controller.rb:467:in `save_issue_with_child_records'
    app/controllers/issues_controller.rb:180:in `update'
WARNING: Can't mass-assign protected attributes for IssueChecklist: is_done, subject
    lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
    lib/redmine/hook.rb:61:in `each'
    lib/redmine/hook.rb:61:in `block in call_hook'
    lib/redmine/hook.rb:58:in `tap'
    lib/redmine/hook.rb:58:in `call_hook'
    lib/redmine/hook.rb:162:in `call_hook'
    app/controllers/issues_controller.rb:478:in `block in save_issue_with_child_records'
    app/controllers/issues_controller.rb:467:in `save_issue_with_child_records'
    app/controllers/issues_controller.rb:180:in `update'
WARNING: Can't mass-assign protected attributes for IssueChecklist: is_done, subject
    lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
    lib/redmine/hook.rb:61:in `each'
    lib/redmine/hook.rb:61:in `block in call_hook'
    lib/redmine/hook.rb:58:in `tap'
    lib/redmine/hook.rb:58:in `call_hook'
    lib/redmine/hook.rb:162:in `call_hook'
    app/controllers/issues_controller.rb:478:in `block in save_issue_with_child_records'
    app/controllers/issues_controller.rb:467:in `save_issue_with_child_records'
    app/controllers/issues_controller.rb:180:in `update'
WARNING: Can't mass-assign protected attributes for IssueChecklist: is_done, subject
    lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
    lib/redmine/hook.rb:61:in `each'
    lib/redmine/hook.rb:61:in `block in call_hook'
    lib/redmine/hook.rb:58:in `tap'
    lib/redmine/hook.rb:58:in `call_hook'
    lib/redmine/hook.rb:162:in `call_hook'
    app/controllers/issues_controller.rb:478:in `block in save_issue_with_child_records'
    app/controllers/issues_controller.rb:467:in `save_issue_with_child_records'
    app/controllers/issues_controller.rb:180:in `update'
WARNING: Can't mass-assign protected attributes for IssueChecklist: is_done, subject
    lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
    lib/redmine/hook.rb:61:in `each'
    lib/redmine/hook.rb:61:in `block in call_hook'
    lib/redmine/hook.rb:58:in `tap'
    lib/redmine/hook.rb:58:in `call_hook'
    lib/redmine/hook.rb:162:in `call_hook'
    app/controllers/issues_controller.rb:478:in `block in save_issue_with_child_records'
    app/controllers/issues_controller.rb:467:in `save_issue_with_child_records'
    app/controllers/issues_controller.rb:180:in `update'
WARNING: Can't mass-assign protected attributes for IssueChecklist: is_done, subject
    lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
    lib/redmine/hook.rb:61:in `each'
    lib/redmine/hook.rb:61:in `block in call_hook'
    lib/redmine/hook.rb:58:in `tap'
    lib/redmine/hook.rb:58:in `call_hook'
    lib/redmine/hook.rb:162:in `call_hook'
    app/controllers/issues_controller.rb:478:in `block in save_issue_with_child_records'
    app/controllers/issues_controller.rb:467:in `save_issue_with_child_records'
    app/controllers/issues_controller.rb:180:in `update'
WARNING: Can't mass-assign protected attributes for IssueChecklist: is_done, subject
    lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
    lib/redmine/hook.rb:61:in `each'
    lib/redmine/hook.rb:61:in `block in call_hook'
    lib/redmine/hook.rb:58:in `tap'
    lib/redmine/hook.rb:58:in `call_hook'
    lib/redmine/hook.rb:162:in `call_hook'
    app/controllers/issues_controller.rb:478:in `block in save_issue_with_child_records'
    app/controllers/issues_controller.rb:467:in `save_issue_with_child_records'
    app/controllers/issues_controller.rb:180:in `update'
Completed 500 Internal Server Error in 83ms (ActiveRecord: 19.7ms)

NoMethodError (undefined method `strip' for nil:NilClass):
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:162:in `call_hook'
  app/controllers/issues_controller.rb:478:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:467:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:180:in `update'
```

**Comment by SolomonFord** [comment]
FWIW, I had the same error and was able to resolve it by adding the following lines to plugins/redmine_issue_checklist/app/models/issue_checklist.rb, somewhere near the top (such as just below 'acts_as_list'):
  attr_accessible :is_done, :subject
  attr_protected :id

...then restart Redmine, and all is well; I was able to close.
